In [1]:
import numpy as np


In [2]:
my_lst = [1,2,3,3,5]

In [3]:
np.array(my_lst)

array([1, 2, 3, 3, 5])

In [7]:
my_array = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((1,1))

array([[1.]])

In [25]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.ones(((2,2,2)))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [36]:
np.linspace(0,6,3)

array([0., 3., 6.])

In [38]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(3,4)

array([[0.11635881, 0.97770833, 0.23239291, 0.67456194],
       [0.56871231, 0.24201573, 0.09185603, 0.72191047],
       [0.09114399, 0.6426497 , 0.55151833, 0.78565414]])

In [40]:
np.random.randn(3,3,3)

array([[[-0.24416896,  1.49979651, -1.16476676],
        [ 0.24143753, -0.07728303, -1.30424872],
        [ 0.00790211, -0.53770524,  0.74004742]],

       [[-0.64211662,  0.06633424,  0.28576679],
        [-0.32405986,  0.49840244,  1.2764749 ],
        [-1.38848255,  0.2542454 , -0.50644109]],

       [[ 2.21156992,  1.01235872, -2.27819574],
        [ 0.06134893, -0.34385849,  1.19810826],
        [-0.27425396,  0.87789751,  0.6532867 ]]])

In [41]:
np.random.randint(2,10)

8

In [42]:
np.random.randint(0,100,50)

array([90, 86, 62, 23, 63, 64, 49, 82, 70, 20, 61, 13, 41,  6,  1,  0, 20,
       22, 70, 20, 32, 95, 70, 87, 33, 40, 68, 43, 69, 83,  9, 20, 29, 50,
       92, 15, 97,  6, 61,  3, 36,  3,  1, 65, 60,  2, 38, 79, 35,  8])

In [47]:
arr= np.arange(25)

In [55]:
ran_arr = np.random.randint(0,50,100)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
ran_arr

array([ 0,  9,  6, 17, 13,  3,  7, 38, 10, 27, 11, 26, 38, 47, 34, 14, 27,
       31, 11,  6, 36,  8, 35, 40, 23, 43, 47, 48, 16, 41, 30, 16, 28, 32,
       37,  5, 40, 14, 15,  9, 47, 48,  0, 46, 29, 16, 25, 47, 14, 19, 16,
       28, 11, 44,  1, 31, 30, 13, 12,  1, 20, 40,  0,  0, 13, 27, 11, 11,
       33, 16, 24, 35,  2, 45, 47, 24, 28, 34, 26, 44, 36,  5, 40, 17, 31,
       14, 37, 15, 11, 22,  7, 49, 38, 17,  1, 46, 48, 42, 16, 10])

In [57]:
ran_arr

array([14, 29,  8, 14, 21, 45, 16,  6, 22, 13, 42, 29, 27, 39, 33, 31, 14,
       39, 14,  6, 28,  9, 13, 32, 42, 24, 47, 37, 34, 29, 27, 17, 21, 32,
       47, 24,  2,  2, 35, 45, 40,  1, 33, 32,  3,  9, 15, 32, 41, 39, 24,
        2, 41, 15,  2, 15, 35, 20, 27, 23, 13,  4, 28, 13,  7, 37, 41, 14,
       22, 35, 35,  4, 40, 46,  1, 31,  2, 30,  9, 48, 23, 13, 31, 42, 42,
       21, 20, 43,  8, 28, 25, 18, 27, 41, 13, 11,  0, 24, 43, 17])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
ran_arr.max()

48

In [59]:
ran_arr.argmax()

79

In [64]:
ran_arr.reshape(10,10).shape

(10, 10)

In [65]:
ran_arr

array([14, 29,  8, 14, 21, 45, 16,  6, 22, 13, 42, 29, 27, 39, 33, 31, 14,
       39, 14,  6, 28,  9, 13, 32, 42, 24, 47, 37, 34, 29, 27, 17, 21, 32,
       47, 24,  2,  2, 35, 45, 40,  1, 33, 32,  3,  9, 15, 32, 41, 39, 24,
        2, 41, 15,  2, 15, 35, 20, 27, 23, 13,  4, 28, 13,  7, 37, 41, 14,
       22, 35, 35,  4, 40, 46,  1, 31,  2, 30,  9, 48, 23, 13, 31, 42, 42,
       21, 20, 43,  8, 28, 25, 18, 27, 41, 13, 11,  0, 24, 43, 17])

In [67]:
ran_arr.reshape(100,1)

array([[14],
       [29],
       [ 8],
       [14],
       [21],
       [45],
       [16],
       [ 6],
       [22],
       [13],
       [42],
       [29],
       [27],
       [39],
       [33],
       [31],
       [14],
       [39],
       [14],
       [ 6],
       [28],
       [ 9],
       [13],
       [32],
       [42],
       [24],
       [47],
       [37],
       [34],
       [29],
       [27],
       [17],
       [21],
       [32],
       [47],
       [24],
       [ 2],
       [ 2],
       [35],
       [45],
       [40],
       [ 1],
       [33],
       [32],
       [ 3],
       [ 9],
       [15],
       [32],
       [41],
       [39],
       [24],
       [ 2],
       [41],
       [15],
       [ 2],
       [15],
       [35],
       [20],
       [27],
       [23],
       [13],
       [ 4],
       [28],
       [13],
       [ 7],
       [37],
       [41],
       [14],
       [22],
       [35],
       [35],
       [ 4],
       [40],
       [46],
       [ 1],
       [31],
       [ 2],

In [68]:
arr_index = np.arange(40)

In [69]:
arr_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [70]:
arr_index [0:5]

array([0, 1, 2, 3, 4])

In [71]:
arr_index[:39]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])

In [72]:
arr_index[30:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [74]:
arr_index[0:5] = '0'

In [75]:
arr_index

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [76]:
arr_index = np.arange(0,40)

In [77]:
sliced_arr = arr_index[1:11]

In [78]:
sliced_arr[:] = 100

In [79]:
sliced_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [80]:
arr_index


array([  0, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39])

In [81]:
arr_index.reshape(4,10)

array([[  0, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]])

In [85]:
arr_index.reshape(1,40)

array([[  0, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39]])

In [86]:
arr_index[0][0] = 100

TypeError: 'numpy.int32' object does not support item assignment

In [87]:
arr_index.reshape(4,10)

array([[  0, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]])

In [90]:
arr_index[:1,10:]

IndexError: too many indices for array

In [105]:
arr_index = np.arange(0,40)

In [106]:
arr_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [107]:
arr_index.reshape(2,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [95]:
arr_index[1:,]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [110]:
arr_index[:1,1:]

IndexError: too many indices for array

In [100]:
arr_index.shape


(40,)

In [111]:
arr_index[1:1,2:3]

IndexError: too many indices for array